podcast:
  title: Drum Tower
  description: "Two of The Economist’s China correspondents, Alice Su and David Rennie, analyse the stories at the heart of this vast country and examine its influence beyond its borders. They’ll be joined by our global network of correspondents and expert guests to examine how everything from party politics to business, technology and culture are reshaping China and the world. Published every Tuesday."
  url: /podcast.xml
  author: The Economist
  email: [podcast email]
  logo: https://www.economist.com/media-assets/image/podcast-image/drumtower.png
  language: en
  category: News
  subcategory: Politics
  type: episodic
  explicit: false
  complete: 'no'
  block: 'no'